project:
  type: website
  output-dir: docs

website:
  title: "António Barros"  
  description: "Biostatistician & Bioinformatician | Faculty of Medicine, University of Porto"
  site-url: https://antoniobarros.github.io 
  
  navbar:
    background: "#2c3e50"
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - href: cv.qmd
        text: CV
      - href: posts.qmd
        text: Blog
    right:
      - icon: envelope
        href: mailto:asbarros@med.up.pt
      - icon: mortarboard
        href: https://orcid.org/0000-0002-9103-5852 

  page-footer:
    background: "#0d2840"
    foreground: light
    center:  © 2026 António Barros 

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools: false
    highlight-style: github
    include-after-body: 
      text:
        <script data-goatcounter="https://abarros.goatcounter.com/count"
        async src="//gc.zgo.at/count.js"></script>

# For academic citations
bibliography: references.bib

execute:
  freeze: auto
